import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` h-full antialiased`}>
      <body className="min-h-full flex flex-col bg-background dot-grid">
        <Header />
        <main className="mx-auto max-w-5xl px-5 py-10">{children}</main>
        <Toaster
          richColors
          duration={5000}
          closeButton
          swipeDirections={["right"]}
          theme="system"
        />
        <footer className="py-5 text-center text-xs text-muted-foreground">
          TaraSet!
        </footer>
      </body>
    </html>
  );
}
